### ISSUE TITLE
Migrate to auto-demands

### ISSUE THREAD

**Issue by balins** [membraneframework/membrane_wav_plugin#12]
We should migrate to auto-demands introduced in version `0.9.0` of `membrane_core` by moving the logic related to partitioning payloads (WAV header, `frames_per_buffer` option) from `handle_demand` to `handle_process_list`.

[MS-80]

[MS-80]: https://membraneframework.atlassian.net/browse/MS-80?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

**Comment by bblaszkow06** [comment]
Closed in #15
